# -*- coding: utf-8 -*-


TABLE_NAME = "tbl_apa"
TABLE_NAME_COL_1_NAME = "field_1"
TABLE_NAME_COL_2_NAME = "field_2"
TABLE_NAME_COL_1_SDL = TABLE_NAME_COL_1_NAME + " SERIAL PRIMARY KEY"
TABLE_NAME_COL_2_SDL = TABLE_NAME_COL_2_NAME + " TEXT"